// Code generated by "stringer -type=status"; DO NOT EDIT

package xethru

import "fmt"

const (
	_status_name_0 = "sleepApp"
	_status_name_1 = "respApp"
)

var (
	_status_index_0 = [...]uint8{0, 8}
	_status_index_1 = [...]uint8{0, 7}
)

func (i status) String() string {
	switch {
	case i == 594911596:
		return _status_name_0
	case i == 594935334:
		return _status_name_1
	default:
		return fmt.Sprintf("status(%d)", i)
	}
}
