// Code generated by "stringer -type=status"; DO NOT EDIT

package xethru

import "fmt"

const _status_name = "respApp"

var _status_index = [...]uint8{0, 7}

func (i status) String() string {
	i -= 594935334
	if i >= status(len(_status_index)-1) {
		return fmt.Sprintf("status(%d)", i+594935334)
	}
	return _status_name[_status_index[i]:_status_index[i+1]]
}
